### ISSUE TITLE
Zhao-carr doesn't restart well

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3gfs-fortran#240]
The zhao-carr scheme spins up quickly when initialized. Notice e.g. these emulator skill plot which compare an emulator to the baseline physics itself. Clearly there is something odd happening in the initial timestep.
![download (9)](https://user-images.githubusercontent.com/1386642/139760396-6cb2d5c1-3473-438d-bb04-44b084919c98.png)

This happens because the GFS physics `Statein` object does not completely capture the state of the physics package. The Zhao-carr microphysics also store some fields in the `Tbd` derived type here:
https://github.com/ai2cm/fv3gfs-fortran/blob/d4fbae12481f5571d1b21f0f3fe35de30b834800/FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90#L4546

@spencerkclark Am I right that this data isn't being saved in the restart files? If so, would it be hard to fix this?

**Comment by spencerkclark** [comment]
I looked into this a little just now.  I believe there is a mechanism for these `Tbd` fields to be saved out in the `phy_data` restart files:
https://github.com/ai2cm/fv3gfs-fortran/blob/d4fbae12481f5571d1b21f0f3fe35de30b834800/FV3/gfsphysics/GFS_layer/GFS_restart.F90#L246-L254
I guess one place that could go wrong is in what number of 3D fields this subroutine expects, i.e. `Model%ntot3d`.  These lines appear relevant for that:
https://github.com/ai2cm/fv3gfs-fortran/blob/d4fbae12481f5571d1b21f0f3fe35de30b834800/FV3/gfsphysics/GFS_layer/GFS_typedefs.F90#L4323

https://github.com/ai2cm/fv3gfs-fortran/blob/d4fbae12481f5571d1b21f0f3fe35de30b834800/FV3/gfsphysics/GFS_layer/GFS_typedefs.F90#L4192-L4199

You are probably more familiar than me with the Zhao-Carr microphysics -- can you tell if the number of 3D physics restart variables is being set properly in this routine?  At least in my read it seems plausible based on the call you referenced in the physics driver.  It could also be interesting to see what the `phy_data` restart files produced by a run with the Zhao-Carr microphysics configuration look like.

**Comment by spencerkclark** [comment]
Nevermind, it would actually have to be consistent:
https://github.com/ai2cm/fv3gfs-fortran/blob/d4fbae12481f5571d1b21f0f3fe35de30b834800/FV3/gfsphysics/GFS_layer/GFS_typedefs.F90#L4913-L4914

**Comment by spencerkclark** [comment]
The fields in the `phy_data` restart files here:
``` 
gs://vcm-ml-experiments/online-emulator/2021-08-09/gfs-initialized-baseline-06/fv3gfs_run/artifacts/20160601.000000/RESTART
```
look like they contain the proper values, i.e. `phy_f3d_01` contains something that looks like a temperature, `phy_f3d_02` contains something that looks like a specific humidity, `phy_f3d_03` contains something that looks like a temperature, and `phy_f3d_04` contains something that looks like a specific humidity.  The `phy_f2d_01` and `phy_f2d_02` fields look like plausible surface pressures as well.

https://github.com/ai2cm/fv3gfs-fortran/blob/d4fbae12481f5571d1b21f0f3fe35de30b834800/FV3/gfsphysics/physics/gscond.f#L53-L85

That seems to suggest that they are being written out appropriately.

**Comment by nbren12** [comment]
Thanks for looking into this. I agree this information is probably being written out well.

**Comment by nbren12** [comment]
I think I found a bug where the Tbd data are overwritten in the first timestep of a simulation for the zhao carr microphysics even if the model is being initialized from restart files:
https://github.com/ai2cm/fv3gfs-fortran/blob/c413bd32c89b9c46460da70451168bbbf984ed2e/FV3/gfsphysics/GFS_layer/GFS_driver.F90#L861


It is charming that this code is buried in a routine titled `rad_time_vary`. It has nothing to do with radiation at all! 

I suspect that fixing this bug will improve the skill aspects of the initialization, but may not make the code exactly bit for bit restartable though. There are numerous weird things in the `GFS_time_vary` subroutine. e.g. restarting from the middle of an hour will give the wrong solar hour: https://github.com/ai2cm/fv3gfs-fortran/blob/c413bd32c89b9c46460da70451168bbbf984ed2e/FV3/gfsphysics/GFS_layer/GFS_driver.F90#L499

cc @spencerkclark

**Comment by nbren12** [comment]
cc @mcgibbon you may be interested too.

**Comment by mcgibbon** [comment]
Wow nice catch!

**Comment by nbren12** [comment]
This branch has some useful code for debugging this checksum issue further. It allows mining the logs to nicely print where state changes happen in the model: https://github.com/ai2cm/fv3gfs-fortran/releases/tag/debug-checksum.

I think I will just fix this bug and move on though.

**Comment by spencerkclark** [comment]
Nice work!  Hopefully this helps the emulation skill.
