### ISSUE TITLE
Merging fv3gfs-wrapper back into this repo

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3gfs-fortran#243]
How do you feel about moving fv3gfs-wrapper into fv3gfs-fortran? How much work would this be? 

I think in practice these repos are still strongly coupled since the wrapper needs deep knowledge of the build flags and internal data structures of fv3gfs. We've done some things to workaround this coupling (e.g. using pkgconfig), but this could make it more challenging to deploy on other platforms. I understand the wrapper could potentially be used with other versions of fv3gfs, but in practice this is not possible because of the build systems + unique changes to the fv3gfs-fortran data structures that we have added (e.g. the surface overrides). 

This is coming up now because @spencerkclark is contemplating running fv3gfs-wrapper+fv3gfs-fortran on other platforms (e.g. GAEA), and could be easier to do if the wrapper was bundled here. By moving the wrapper into this repo, we could build it easily by running e.g. `cd FV3 &&  make build_wrapper_wheel` and not resort to pkgconfig or makefiles importing one another.

Another concern is that the wrapper repo is not being actively maintained in its current home. It has not been updated since May 6, so it is hard to know if it is keeping track with the ongoing changes to e.g. typedefs here.

cc @spencerkclark @mcgibbon

**Comment by mcgibbon** [comment]
In principle I think this is a good idea. Would want to poll everyone for any ideas of potential issues. If we do this, it should wait until after the Pace monorepo has been created and I have more information about whether the wrapper will be included in that repo. I also think if we merge repos we should still try to keep the Fortran code/build as untouched as possible by the inclusion of the wrapper, as it is now.

**Comment by mcgibbon** [comment]
To give some idea of when that will be, we're trying to get the mono-repo created/merged in by the end of next week.

**Comment by nbren12** [comment]
This is done.
