### ISSUE TITLE
Circle CI ubuntu 16.04 machines end of life

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3gfs-fortran#283]
> We are deprecating Ubuntu 16.04-based machine images on CircleCI in preparation for an EOL on Tuesday, May 31, 2022 to ensure your builds remain secure. For more details and a complete schedule of the timeline, [please see our blog post.](https://go.circleci.com/NDg1LVpNSC02MjYAAAGD54ir_3Isn_OGUDCChe64hM6IK02_DSvqrne0h4HSA-eg9SiYbpiAfCJaxAoA-3hL-cBvfTE=).

**Comment by brianhenn** [comment]
Getting closer, some images builds failing today due to "brownouts"

**Comment by nbren12** [comment]
:(

**Comment by elynnwu** [comment]
This might fix it 🤞 
https://github.com/ai2cm/fv3gfs-fortran/pull/295

**Comment by brianhenn** [comment]
Appears to be resolved by #295
