### ISSUE TITLE
Broken symlink causing issues downstream

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/fv3gfs-fortran#320]
There is a symlink that points to a path outside the repo, and this is causing issues downstream:

```
(fv3net) oliverwm@OliverWeyersMBP daint_multi_node % pwd
/Users/oliverwm/repos/fv3gfs-fortran/benchmarking/daint_multi_node
(fv3net) oliverwm@OliverWeyersMBP daint_multi_node % ls -lh scratch
lrwxr-xr-x  1 oliverwm  staff    35B Sep  1  2021 scratch -> /scratch/snx3000/olifu/benchmarking
```

See https://github.com/ai2cm/fv3net/issues/2018

**Comment by AnnaKwa** [comment]
Pinning the image to `ubuntu-20.04` worked for a bit, but the broken symlink issue has popped up again: https://app.circleci.com/pipelines/github/ai2cm/fv3net/13505/workflows/976e8749-2cf3-4928-8db7-37e1955f8793/jobs/124438

I guess we should just get rid of the symlinks to permanently fix this.
